site_name: Flexpa OS
site_url: https://os.flexpa.com
theme:
  name: material
  palette:
    scheme: default
    primary: green
    accent: green
  logo: assets/logo.png
  features:
    - navigation.sections
    - content.action.edit
extra:
  homepage: https://flexpa.com
  generator: false
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/flexpa
    - icon: fontawesome/brands/github 
      link: https://github.com/flexpa
repo_url: https://github.com/flexpa/os
repo_name: flexpa/os
edit_uri: edit/master/docs/
markdown_extensions:
  - admonition
  - tables
nav:
  - ...
  - Process:
    - ... | flat | process/*.md
  - Policy:
    - ... | flat | policy/*.md
  - People:
    - ... | flat | people/*.md
  - IT:
    - ... | flat | it/*.md
plugins:
  - awesome-pages